---
spring:
  profiles: dev
eureka:
  instance:
      hostname: @@@@@@
  client:
   serviceUrl:
      defaultZone: http://@@@@@:@@@@@!@@lgb4902.@@@@@@@.com:8761/eureka/
---
spring:
  profiles: local
eureka:
  instance:
      hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
