info:
  component: zuul server app

server:
  port: 8080

spring:
   config:
      name:  zuulserver
   application:
      name:  zuulserver
      
zuul:
  routes:
    strings:
      path: /ech/**
      serviceId: microServiceEcho
    locations:
      path: /locate/**
      serviceId: MicroServiceLocator
    stores:
      path: /stores/**
      serviceId: MicroServiceStores
      
error:
  whitelabel:
    enabled:false
